package com.hiddenly.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

// This class represents the 'spots' table in our MySQL database.
// Each spot is a hidden location shared by a user.
@Entity
@Table(name = "spots")
public class Spot {

    // The unique ID of the spot, automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The name of the spot (e.g., "Art Cafe").
    @Column(nullable = false)
    private String name;

    // A detailed description of why this spot is special.
    // @Column(columnDefinition = "TEXT") allows for very long descriptions.
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    // The location/address of the spot.
    @Column(nullable = false, length = 1000)
    private String location;

    // The category of the spot (CAFE, NATURE, FOOD, ADVENTURE).
    @Column(nullable = false)
    private String category;

    // The budget range (e.g., "Under ₹200", "Under ₹500", "₹500+").
    @Column(name = "budget_range")
    private String budgetRange;

    // A URL for an image of the spot.
    // We increase the length to 1000 characters because some search engine URLs are very long.
    @Column(name = "image_url", length = 1000)
    private String imageUrl;

    // The recommended number of persons for this spot.
    @Column(name = "persons_count")
    private Integer personsCount;

    // The user who added this spot.
    // @ManyToOne means many spots can be added by one user.
    // @JoinColumn specifies the foreign key column name in the database.
    @ManyToOne
    @JoinColumn(name = "added_by_user_id", nullable = false)
    private User addedBy;

    // The average rating of the spot (starts at 0.0).
    @Column(name = "average_rating")
    private Double averageRating = 0.0;

    // When the spot was added.
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();

    // Coordinates for Google Maps
    @Column(name = "latitude")
    private Double latitude;

    @Column(name = "longitude")
    private Double longitude;

    // --- CONSTRUCTORS ---

    // Required by JPA
    public Spot() {}

    // Parametrized constructor for easy spot creation
    public Spot(String name, String description, String location, String category, String budgetRange, String imageUrl, User addedBy) {
        this.name = name;
        this.description = description;
        this.location = location;
        this.category = category;
        this.budgetRange = budgetRange;
        this.imageUrl = imageUrl;
        this.addedBy = addedBy;
    }

    // --- GETTERS AND SETTERS ---

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getBudgetRange() { return budgetRange; }
    public void setBudgetRange(String budgetRange) { this.budgetRange = budgetRange; }

    public String getImageUrl() { return imageUrl; }
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }

    public Integer getPersonsCount() { return personsCount; }
    public void setPersonsCount(Integer personsCount) { this.personsCount = personsCount; }

    public User getAddedBy() { return addedBy; }
    public void setAddedBy(User addedBy) { this.addedBy = addedBy; }

    public Double getAverageRating() { return averageRating; }
    public void setAverageRating(Double averageRating) { this.averageRating = averageRating; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public Double getLatitude() { return latitude; }
    public void setLatitude(Double latitude) { this.latitude = latitude; }

    public Double getLongitude() { return longitude; }
    public void setLongitude(Double longitude) { this.longitude = longitude; }
}
